position = { # Specifiy the market parameters to run over -- many different examples provided below
    "Generalised_position_0.002_1_USDC" : {
        "rate_ranges": [(0.002, 1)],
        "fr_markets": ["neutral", "bear", "bull"],
        "f_values": [0.5, 1, 2, 5, 7.5, 10, 20], 
        "notional": 1000,
        "pool_size": 60,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "leverage_factors": [1],
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["USDC"]
    },
    "Generalised_position_1_10_USDC" : {
        "rate_ranges": [(1, 10)],
        "fr_markets": ["neutral", "bear", "bull"],
        "f_values": [0.5, 1, 2, 5, 7.5, 10, 20], 
        "notional": 1000,
        "pool_size": 60,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "leverage_factors":[1],
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["USDC"]
    },
    "Generalised_position_0.002_1_DAI" : {
        "rate_ranges": [(0.002, 1)],
        "fr_markets": ["neutral", "bear", "bull"],
        "f_values": [0.5, 1, 2, 5, 7.5, 10, 20], 
        "notional": 1000,
        "pool_size": 60,
        "gamma_fee": 0.003,
        "leverage_factors": [1],
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["DAI"]
    },
    "Generalised_position_1_10_DAI" : {
        "rate_ranges": [(1, 10)],
        "fr_markets": ["neutral", "bear", "bull"],
        "f_values": [0.5, 1, 2, 5, 7.5, 10, 20], 
        "notional": 1000,
        "pool_size": 60,
        "gamma_fee": 0.003,
        "leverage_factors": [1],
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["DAI"]
    },
    "Generalised_position_trials" : {
        "rate_ranges": [(1, 10)],
        "fr_markets": ["neutral", "bear", "bull"],
        "f_values": [0.5, 10], 
        "notional": 1000,
        "pool_size": 60,
        "gamma_fee": 0.003,
        "leverage_factors": [1],
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["USDC", "DAI"]
    },
    "Generalised_position_many_ticks_USDC_with_std_July2022_with_gap_lookback_new_apy" : {
        "rate_ranges": [(0.002, 1), (1, 3), (3, 10)],
        "fr_markets": ["neutral", "bear", "bull"],
        "f_values": [0.5, 1, 2, 3, 5], 
        "leverage_factors": [1],
        "notional": 1000,
        "pool_size": 62,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["USDC"]
    },
    "Generalised_position_many_ticks_DAI_with_std_July2022_with_gap_lookback_new_apy" : {
        "rate_ranges": [(0.002, 1), (1, 3), (3, 10)],
        "fr_markets": ["neutral", "bear", "bull"],
        "f_values": [0.5, 1, 2, 3, 5], 
        "leverage_factors": [1],
        "notional": 1000,
        "pool_size": 62,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["DAI"]
    },
    "Generalised_position_many_ticks_USDC_with_std_July2022_with_gap_lookback_single_tick" : {
        "rate_ranges": [(1, 5)],
        "fr_markets": ["neutral", "bear", "bull"],
        "f_values": [0.5, 1, 2, 3, 5], 
        "leverage_factors": [1],
        "notional": 1000,
        "pool_size": 62,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["USDC"]
    },
    "Generalised_position_many_ticks_DAI_with_std_July2022_with_gap_lookback_single_tick" : {
        "rate_ranges": [(1, 5)],
        "fr_markets": ["neutral", "bear", "bull"],
        "f_values": [0.5, 1, 2, 3, 5], 
        "leverage_factors": [1],
        "notional": 1000,
        "pool_size": 62,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["DAI"]
    },
    "Generalised_position_many_ticks_USDC_with_std_July2022" : {
        "rate_ranges": [(0.002, 1), (1, 3), (3, 10)],
        "fr_markets": ["neutral", "bear", "bull"],
        "f_values": [0.5, 1, 2, 3, 5], 
        "leverage_factors": [1],
        "notional": 1000,
        "pool_size": 62,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["USDC"]
    },
    "Generalised_position_many_ticks_DAI_with_std_July2022" : {
        "rate_ranges": [(0.002, 1), (1, 3), (3, 10)],
        "fr_markets": ["neutral", "bear", "bull"],
        "f_values": [0.5, 1, 2, 3, 5], 
        "leverage_factors": [1],
        "notional": 1000,
        "pool_size": 62,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["DAI"]
    },
    "Single_Position_DAI" : {
        "rate_ranges": [(0.2,1)],
        "fr_markets": ["neutral"],
        "f_values": [1], 
        "leverage_factors": [1],
        "notional": 1000,
        "pool_size": 62,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["DAI"]
    },
    "Single_Position_USDC" : {
        "rate_ranges": [(0.2,5)],
        "fr_markets": ["neutral"],
        "f_values": [1], 
        "leverage_factors": [1],
        "notional": 1000,
        "pool_size": 62,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["USDC"]
    },
    "Generalised_position_many_ticks_rETH_with_std" : {
        "rate_ranges": [(0.002, 1), (1, 3), (3, 10)],
        "fr_markets": ["neutral", "bear", "bull"],
        "f_values": [0.5, 1, 2, 3, 5], 
        "leverage_factors": [1],
        "notional": 1000,
        "pool_size": 180,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["rETH"]
    },
    "Generalised_position_many_ticks_stETH_with_std" : {
        "rate_ranges": [(0.002, 1), (1, 3), (3, 10)],
        "fr_markets": ["neutral", "bear", "bull"],
        "f_values": [0.5, 1, 2, 3, 5], 
        "leverage_factors": [1],
        "notional": 1000,
        "pool_size": 180,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["stETH"]
    },
    "RiskEngineOptimisationV2_stETH_LMOpt" : {
        "rate_ranges": [(1, 5)],
        #"fr_markets": ["neutral", "bear", "bull"],
        "fr_markets": ["neutral"],
        "f_values": [5], 
        "leverage_factors": [1],
        "notional": 1000,
        "pool_size": 180,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["stETH"]
    },
    "RiskEngineOptimisationV2_rETH_LMOpt" : {
        "rate_ranges": [(1, 5)],
        #"fr_markets": ["neutral", "bear", "bull"],
        "fr_markets": ["neutral"],
        "f_values": [5], 
        "leverage_factors": [1],
        "notional": 1000,
        "pool_size": 180,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["rETH"]
    },
    "leverage_positions_USDC" : {
        "rate_ranges": [(1,3)], 
        "fr_markets": ["neutral"],
        "f_values": [1], 
        "notional": 1000,
        "pool_size": 60,
        "leverage_factors": [1, 1.5, 2.5, 5, 7.5, 10, 25, 50, 75, 100, 500],
        "gamma_fee": 0.003,
        "gamma_fees": [0.0003, 0.0005, 0.0007, 0.001, 0.0015, 0.002, 0.003, 0.005, 0.007, 0.01, 0.015, 0.02, 0.03],
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["USDC"]
    },
    "leverage_positions_DAI" : {
        "rate_ranges": [(1, 10)], 
        "fr_markets": ["neutral"],
        "f_values": [1, 10, 20], 
        "notional": 1000,
        "pool_size": 60,
        "leverage_factors": [1, 1.5, 2.5, 5, 7.5, 10, 25, 50, 75, 100, 500],
        "gamma_fee": 0,
        "gamma_fees": [0.0003, 0.0005, 0.0007, 0.001, 0.0015, 0.002, 0.003, 0.005, 0.007, 0.01, 0.015, 0.02, 0.03],
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["DAI"]
    },
    "Optimised_test_rETH" : {
        "rate_ranges": [(1,3)], 
        "fr_markets": ["neutral"],
        "f_values": [1], 
        "notional": 1000,
        "pool_size": 180,
        "leverage_factors": [1],
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["rETH"]
    },
    "Optimised_test_stETH" : {
        "rate_ranges": [(1,3)], 
        "fr_markets": ["neutral"],
        "f_values": [1], 
        "notional": 1000,
        "pool_size": 180,
        "leverage_factors": [1],
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["stETH"]
    },
    "Generalised_position_many_ticks_stETH_with_std_FT_lev_reg" : {
        "rate_ranges": [(0.002, 1), (1, 3), (3, 10)],
        "fr_markets": ["neutral", "bear", "bull"],
        "f_values": [0.5, 1, 2, 3, 5], 
        "leverage_factors": [1],
        "notional": 1000,
        "pool_size": 180,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["stETH"]
    },
    "Generalised_position_many_ticks_rETH_with_std_FT_lev_reg" : {
        "rate_ranges": [(0.002, 1), (1, 3), (3, 10)],
        "fr_markets": ["neutral", "bear", "bull"],
        "f_values": [0.5, 1, 2, 3, 5], 
        "leverage_factors": [1],
        "notional": 1000,
        "pool_size": 180,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["rETH"]
    },
    "Generalised_position_many_ticks_stETH_with_std_FT_lev_reg_optimised" : {
        "rate_ranges": [(0.002, 1), (1, 3), (3, 10)],
        "fr_markets": ["neutral", "bear", "bull"],
        "f_values": [0.5, 1, 2, 3, 5], 
        "leverage_factors": [1],
        "notional": 1000,
        "pool_size": 180,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["stETH"]
    },
    "Generalised_position_many_ticks_rETH_with_std_FT_lev_reg_optimised_CIR_check" : {
        "rate_ranges": [(0.002, 1), (1, 3), (3, 10)],
        "fr_markets": ["neutral", "bear", "bull"],
        "f_values": [0.5, 1, 2, 3, 5], 
        "leverage_factors": [1],
        "notional": 1000,
        "pool_size": 180,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["rETH"]
    },
    "Generalised_position_many_ticks_rETH_with_std_FT_lev_reg_optimised" : {
        "rate_ranges": [(0.002, 1), (1, 3), (3, 10)],
        "fr_markets": ["neutral", "bear", "bull"],
        "f_values": [0.5, 1, 2, 3, 5], 
        "leverage_factors": [1],
        "notional": 1000,
        "pool_size": 180,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["rETH"]
    },
    "RiskEngineOptimisation_borrow_aUSDC_7_months_FTLev" : {
        "rate_ranges": [(1, 5)],
        #"fr_markets": ["neutral", "bear", "bull"],
        "fr_markets": ["neutral"],
        "f_values": [5], 
        "leverage_factors": [1],
        "notional": 1000,
        "pool_size": 210,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["USDC"]
    },
    "RiskEngineOptimisation_borrow_aWETH_7_months" : {
        "rate_ranges": [(1, 5)],
        "fr_markets": ["neutral"],
        #"fr_markets": ["neutral", "bear", "bull"],
        "f_values": [5], 
        "leverage_factors": [1],
        "notional": 1000,
        "pool_size": 210,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["WETH"]
    },
    "RiskEngineOptimisation_borrow_cUSDT_7_months_FTLev" : {
        "rate_ranges": [(1, 5)],
        "fr_markets": ["neutral"],
        #"fr_markets": ["neutral", "bear", "bull"],
        "f_values": [5], 
        "leverage_factors": [1],
        "notional": 1000,
        "pool_size": 210,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["USDT"]
    },
    "RiskEngineOptimisation_borrow_cETH_7_months" : {
        "rate_ranges": [(1, 5)],
        "fr_markets": ["neutral", "bear", "bull"],
        "f_values": [5], 
        "leverage_factors": [1],
        "notional": 1000,
        "pool_size": 210,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["ETH"]
    },
    "RiskEngineOptimisation_borrow_aUSDC_4_months_FTLev" : {
        "rate_ranges": [(1, 5)],
        "fr_markets": ["neutral"],
        "f_values": [5], 
        "leverage_factors": [1],
        "notional": 1000,
        "pool_size": 120,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["USDC"]
    },
    "RiskEngineOptimisation_borrow_aWETH_4_months_FTLev" : {
        "rate_ranges": [(1, 5)],
        #"fr_markets": ["neutral", "bear", "bull"],
        "fr_markets": ["neutral"],
        "f_values": [5], 
        "leverage_factors": [1],
        "notional": 1000,
        "pool_size": 120,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["WETH"]
    },
    "RiskEngineOptimisation_borrow_cUSDT_4_months_FTLev" : {
        "rate_ranges": [(1, 5)],
        "fr_markets": ["neutral"],
        "f_values": [5], 
        "leverage_factors": [1],
        "notional": 1000,
        "pool_size": 120,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["USDT"]
    },
    "RiskEngineOptimisation_borrow_cETH_4_months" : {
        "rate_ranges": [(1, 5)],
        "fr_markets": ["neutral"],
        "f_values": [5], 
        "leverage_factors": [1],
        "notional": 1000,
        "pool_size": 120,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["ETH"]
    },
}