position = { # Specifiy the market parameters to run over -- many different examples provided below
    "RiskEngineOptimisation_borrow_aUSDC_V2" : {
        "rate_ranges": [(1, 5)],
        "fr_markets": ["neutral"],
        #"fr_markets": ["neutral", "bear", "bull"],
        #"f_values": [10], 
        "f_values": [1], 
        "leverage_factors": [1],
        "notional": 1000,
        "pool_size": 210,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["USDC"]
    },
    "RiskEngineOptimisation_borrow_aWETH_V2" : {
        "rate_ranges": [(1, 5)],
        #"fr_markets": ["neutral", "bear", "bull"],
        "fr_markets": ["neutral"],
        #"f_values": [10], 
        "f_values": [1], 
        "leverage_factors": [1],
        "notional": 1000,
        "pool_size": 120,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["WETH"]
    },
    "RiskEngineOptimisation_borrow_cUSDT_V2" : {
        "rate_ranges": [(1, 5)],
        "fr_markets": ["neutral"],
        #"fr_markets": ["neutral", "bear", "bull"],
        #"f_values": [10], 
        "f_values": [1], 
        "leverage_factors": [1],
        "notional": 1000,
        "pool_size": 210,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["USDT"]
    },
    "RiskEngineOptimisation_lend_aUSDC_V2" : {
        "rate_ranges": [(1, 5)],
        "fr_markets": ["neutral"],
        #"fr_markets": ["neutral", "bear", "bull"],
        #"f_values": [10], 
        "f_values": [1], 
        "leverage_factors": [1],
        "notional": 1000,
        "pool_size": 62,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["USDC"]
    },
    "RiskEngineOptimisation_lend_aUSDC_V3": {
        "rate_ranges": [(1, 5)],
        "fr_markets": ["neutral"],
        # "fr_markets": ["neutral", "bear", "bull"],
        # "f_values": [10],
        "f_values": [1],
        "leverage_factors": [1],
        "notional": 1000,
        "pool_size": 62,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["USDC"]
    },
    "RiskEngineOptimisation_lend_cDAI_V2" : {
        "rate_ranges": [(1, 5)],
        "fr_markets": ["neutral"],
        #"fr_markets": ["neutral", "bear", "bull"],
        #"f_values": [10], 
        "f_values": [1], 
        "leverage_factors": [1],
        "notional": 1000,
        "pool_size": 62,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["DAI"]
    },
    "RiskEngineOptimisation_lend_aDAI_V2" : {
        "rate_ranges": [(1, 5)],
        "fr_markets": ["neutral"],
        #fr_markets": ["neutral", "bear", "bull"],
        #"f_values": [10], 
        "f_values": [1], 
        "leverage_factors": [1],
        "notional": 1000,
        "pool_size": 62,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["DAI"]
    },
    "RiskEngineOptimisation_lend_stETH_V2" : {
        "rate_ranges": [(1, 5)],
        #"fr_markets": ["neutral", "bear", "bull"],
        "fr_markets": ["neutral"],
        #"f_values": [10], 
        "f_values": [1], 
        "leverage_factors": [1],
        "notional": 1000,
        "pool_size": 180,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["stETH"]
    },
    "RiskEngineOptimisation_lend_rETH_V2" : {
        "rate_ranges": [(1, 5)],
        #"fr_markets": ["neutral", "bear", "bull"],
        "fr_markets": ["neutral"],
        #"f_values": [10], 
        "f_values": [1], 
        "leverage_factors": [1],
        "notional": 1000,
        "pool_size": 180,
        "gamma_fee": 0.003,
        "gamma_fees": None,
        "lp_fix": 0,
        "lp_var": 0,
        "tokens": ["rETH"]
    },
}